#include <fstream>
#include <iostream>
#include <sstream>
#include "lexer.h"
#include "parser.h"

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <sample_program_file>\n";
        return 1;
    }

 
    std::ifstream in(argv[1]);
    if (!in) {
        std::cerr << "Error: cannot open " << argv[1] << "\n";
        return 1;
    }
    std::stringstream buffer;
    buffer << in.rdbuf();

    
    std::vector<Token> tokens = tokenize(buffer.str());
    printTokens(tokens);
    std::cout << "\n";


    Parser parser(tokens);
    std::string error;
    bool ok = parser.parse(error);

    
    if (ok) {
        std::cout << "The Sample Program is generated by the BNF grammar\n";
    } else {
        std::cout << "The Sample Program cannot be generated by the LearnCompiler BNF Grammar\n";
        std::cout << error << "\n";
    }
    return 0;
}
